backend:
  name: git-gateway
  branch: main

media_folder: "public/assets"
public_folder: "/assets"

collections:
  - name: "blog"
    label: "Blogs"
    folder: "src/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
     - { label: "Title", name: "title", widget: "string"}
     - { label: "Description", name: "description", widget: "string"}
     - { label: "Tags", name: "tags", widget: "list", default: ["blog"]}
     - { label: "Featured Image", name: "image", widget: "image"}
     - { label: "Image Caption", name: "imgAlt", widget: "string"}
     - { label: "Body", name: "body", widget: "markdown"}

- name: "Videos"
  label: "Videos"
  folder: "src/podcast"
  create: true
  slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
  fields:
    - { label: "Title", name: "title", widget: "string"}
    - { label: "Tags", name: "tags", widget: "list", default: ["pods"]}
    - { label: "Video", name: "video", widget: "url"}
    - { label: "Body", name: "body", widget: "markdown"}